spring:
  application:
    name: organization
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb.${NAMESPACE}/${MONGO_DATABASE}
  cloud:
    kubernetes:
      client:
       namespace: ${NAMESPACE}

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

feign:
  department:
    name: department
    url:
  employee:
    name: employee
    url:

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
