---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{service}}
  namespace: {{namespace}}
  labels:
    app: {{service}}
    redeploy: {{version}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{service}}
  template:
    metadata:
      labels:
        app: {{service}}
    spec:
      containers:
      - name: {{service}}
        image: {{image}}
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodb
              key: database-name
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-user
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-password
---
apiVersion: v1
kind: Service
metadata:
  name: {{service}}
  namespace: {{namespace}}
  labels:
    app: {{service}}
    spring-boot: "true"
spec:
  ports:
  - name: port-gateway
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: port-admin
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{service}}